### ISSUE TITLE
The ability to pause an incense

### ISSUE THREAD

**Issue by DesmondWhisper** [poketwo/poketwo#147]
Sometimes I feel like running an incense but I don't really feel like sticking around for an entire hour. It would be great if I could pause the incense for a few hours and than finish it up later. Of course this kind of feature would never be a necessity, would simply be a nice thing to have. Or perhaps making a smaller incense that only lasts a half hour and costs half the shards.

**Comment by cillosis** [comment]
Although this has been brought up many times, I had an idea to propose to solve this asbit also goes hand-in-hand with the issue of how to resume incense that have been interrupted when the bot experiences issues.

Currently incense is time based. Like overall duration is 1 hour and spawns occur roughly every 20 seconds I think. If instead of storing a start time and running into the issue of the incense end time being reached prematurely due to downtime or not getting all the spawns due to bot slowdown or discord api issues, we instead make it integer based.

By this, I mean 1 incense = 180 guaranteed spawns (3 per minute for 60 minutes). The storage mechanism would store *spawns remaining*. Each time a spawn is made, the counter is decremented. This does the following:

- Allows the bot to resume with spawns remaining upon downtime.
- Allows the incense to potentially run a little longer in the event of bot/discord latency issues. This ensures the user doesn't feel cheated outnof spawns from something out of our control.
- Allows us to pause the spawn loop via a status and resume it later, and it will continue decrementing where it left off.

I do think the pause should come with something like a 24 hour expiry and DM the user to resume within 1 hour or it will automatically resume just so there doesn't end up a backlog of paused incense.

Thoughts?

**Comment by InkeyRoll** [comment]
So can you pause and start back?

**Comment by notevenayaan** [comment]
you could just kick the bot when u want to pause, and reinvite it wen u want to start again. my friend told me this and it works fine for him. i havent tried it yet cus im broke but i will later..

**Comment by BrainNotFoundException** [comment]
> Although this has been brought up many times, I had an idea to propose to solve this a it also goes hand-in-hand with the issue of how to resume incense that have been interrupted when the bot experiences issues.
> 
> Currently incense is time based. Like overall duration is 1 hour and spawns occur roughly every 20 seconds I think. If instead of storing a start time and running into the issue of the incense end time being reached prematurely due to downtime or not getting all the spawns due to bot slowdown or discord api issues, we instead make it integer based.
> 
> By this, I mean 1 incense = 180 guaranteed spawns (3 per minute for 60 minutes). The storage mechanism would store _spawns remaining_. Each time a spawn is made, the counter is decremented. This does the following:
> 
> * Allows the bot to resume with spawns remaining upon resuming from downtime.
> * Allows the incense to potentially run a little longer in the event of bot/discord latency issues. This ensures the user doesn't feel cheated out of spawns from something out of our control.
> * Allows us to pause the spawn loop via a status and resume it later, and it will continue decrementing where it left off.
> 
> I do think the pause should come with something like a 24 hour expiry and DM the user to resume within 1 hour or it will automatically resume just so there doesn't end up a backlog of paused incense, but that may not be an issue. Maybe instead it just sends a DM every 24 hours to remind them to resume.
> 
> Thoughts?

yea this would be good an option to pause the incense but with a 24 hour expiry

**Comment by WitherredAway** [comment]
> > Although this has been brought up many times, I had an idea to propose to solve this a it also goes hand-in-hand with the issue of how to resume incense that have been interrupted when the bot experiences issues.
> > Currently incense is time based. Like overall duration is 1 hour and spawns occur roughly every 20 seconds I think. If instead of storing a start time and running into the issue of the incense end time being reached prematurely due to downtime or not getting all the spawns due to bot slowdown or discord api issues, we instead make it integer based.
> > By this, I mean 1 incense = 180 guaranteed spawns (3 per minute for 60 minutes). The storage mechanism would store _spawns remaining_. Each time a spawn is made, the counter is decremented. This does the following:
> > 
> > * Allows the bot to resume with spawns remaining upon resuming from downtime.
> > * Allows the incense to potentially run a little longer in the event of bot/discord latency issues. This ensures the user doesn't feel cheated out of spawns from something out of our control.
> > * Allows us to pause the spawn loop via a status and resume it later, and it will continue decrementing where it left off.
> > 
> > I do think the pause should come with something like a 24 hour expiry and DM the user to resume within 1 hour or it will automatically resume just so there doesn't end up a backlog of paused incense, but that may not be an issue. Maybe instead it just sends a DM every 24 hours to remind them to resume.
> > Thoughts?
> 
> yea this would be good an option to pause the incense but with a 24 hour expiry

That is a good suggestion. However, that comment is a year old and fortunately, incenses are not time-based and does work the way suggested (anymore atleast) if I'm not mistaken. You can pause incenses by kicking the bot because it is amount of spawns left based and not time based.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L40
Here is the code for incense spawning.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L42
On this line, it looks for all channels of all servers (in the database) that have greater than 0 incense spawns left, and it stores it in a variable.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L45
Here, for each channel, it checks if the bot is in the server that channel belongs to. If it is not in the server, the bot skips this channel and goes to the next channel in the list. *This is the piece if code that makes it possible to pause incenses by kicking the bot.*

**Comment by WitherredAway** [comment]
> yea this would be good an option to pause the incense but with a 24 hour expiry

That is a good suggestion. However, that comment is a year old and fortunately, incenses are not time-based and does work the way suggested (anymore atleast) if I'm not mistaken. You can pause incenses by kicking the bot because it is amount of spawns left based and not time based.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L40
Here is the code for incense spawning.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L42
On this line, it looks for all channels of all servers (in the database) that have greater than 0 incense spawns left, and it stores it in a variable.

https://github.com/poketwo/poketwo/blob/06a253bcf1f5c894073393d845a423ac289873c7/cogs/spawning.py#L45
Here, for each channel, it checks if the bot is in the server that channel belongs to. If it is not in the server, the bot skips this channel and goes to the next channel in the list. *This is the piece of code that makes it possible to pause incenses by kicking the bot.*
