### ISSUE TITLE
Duplicate Pokemon Glitch

### ISSUE THREAD

**Issue by JustTom7** [poketwo/poketwo#185]
Pokemon can be traded away, but also kept by the previous owner; allowing the previous owner to level up with XP, drop held items, buy rare candy and evolution items for the pokemon, which will effect the new owners Pokemon.

**To Reproduce**
User A: Seller
User B: Buyer

- User A and User B start a trade.
- User A adds a Pokemon to the trade.
- User A then selects the Pokemon.
- The trade is completed.

User A can use p!info and still shows the Pokemon but it won't show up when searched via p!p. User A can gain XP for this pokemon through normal talking, or buy a rare candy for the pokemon amongst other things, and it will directly effect user B's pokemon. This bug is most harmful for mint shinies. The Pokemon will stay as User A's selected pokemon until they select something else.

**Solution**
The solution would be to either not allow your selected Pokemon to be changed whilst in a trade at all, or to not allow specifically Pokemon that are in the trade to be selected.

**Comment by person583375239** [comment]
Nice find

**Comment by Kuraven** [comment]
I've done this before. As you said, the pokemon you have selected disappears once you select a different pokemon. That's not duping. You can't add selected pokemon to trades, auctions, or the market, meaning that as soon as you try to switch to another pokemon to add the previously selected one to the market, it's going to disappear and prevent you from adding it. :I

**Comment by JustTom7** [comment]
> Edit: Also, I'm getting the slightest idea that you actually know this and that you're just a clout chaser, because let's be real; no one would legitimately report this without duping their own stuff a dozen times.

Yes, I know very well that it doesn't actually 'duplicate' the pokemon, but it appears as if it has been. That doesn't make it not an issue? Would you like me to rename this 'Items appear as though they have been duplicated but haven't actually been duplicated', seems like you just want to nit-pick.

I am a mint shiny collector, with 140 mint level 1 shinies. The reason for reporting this is because I would not like someone to level up my shiny after the trade, making my mint shiny no longer mint. Image being called a 'clout chaser' for reporting an issue, toxicity at its finest.

**Comment by person583375239** [comment]
@Kuraven Rerporting an issue for any software is legitimate. The comment about clout-chasing is unecessary

The title is accurate imo, because the pokemon is actually duplicated _in a sense_

**Comment by Kuraven** [comment]
Yea sorry about the clout chase thing. People have done it here before with false claims of duping and cheats and stuff, so I thought it was a similar situation

But also, yeah I just tested it, and this would be a really big issue cuz I actually missed the part where you mentioned how you can level up the pokemon after it's been traded. I just tested it again, but I bought a rare candy and it _did_  evolve the pokemon I traded to my alt, so this would def be used by scammers to troll people and could cause issues even if the intent to do so isn't there

**Comment by michaelsong4399** [comment]
@JustTom7 Thank you for the bug report. This is unintended behavior for the bot and will be patched shortly. This is a real issue and there's no need for name calling here.

For the above conversation - the Pokemon is not, and can never be duplicated in Poketwo, simply because there isn't a duplicating function for each Pokemon. What is actually happening is by `p!select`ing the Pokemon's "inventory" ID, the user is pointing `p!i` to the actual Pokemon ID, which stays there for the future `p!i` events. The player is thus able to access the Pokemon without it being in his "inventory." Now, `p!t` or `p!m a` commands are not affected because they have already been trade-blocked. We will probably be adding the trade-block to `p!select and p!favorite` shortly. There might be a need to add owner-check for all the pokemon.py (or shop, market, and trading) commands depending on Oliver's opinion.
