### ISSUE TITLE
Make pokedex register pokemon that you haven't caught

### ISSUE THREAD

**Issue by MrSoundless** [poketwo/poketwo#203]
The pokedex currently only registers pokemon you've caught. If you catch a pokemon and evolve it, it doesn't get registered. If you trade a pokemon, it's not registered. Even your starter pokemon isn't registered.

That's not how a pokedex works in any of the games.

The solution would be to have the pokedex register all those above mentioned pokemon too.

**Comment by S3any23** [comment]
I agree wholeheartedly

**Comment by WitherredAway** [comment]
This feature is in consideration.

But I'd like to point out a few things. In the actual games, catching Pokemon is a lot more work than just typing p!c <name>. And getting Pokemon to spawn is also a lot easier in poketwo too. So in contrast, it's a lot easier to complete Dex in poketwo than the actual games. 

If evolutions, trades and boxes contributed to dex, that would make it way too easy to complete dex, and might even make it no longer fun for some people (I personally  
think it's fine the way it is right now.) If it was made that easy to complete Dex, poketwo would probably lose some player retention, because it's quite a challenge to complete it and a reason to keep playing. 

Moreover, if trades and evolution added to dex, it would make it WAY easier to get the dex milestones (10, 100, 1000, etc). I mean you could just keep trading one Pokemon continuously back and forth on an alt and get the 100,000 milestone pretty easily.

**Comment by kyle-he** [comment]
This is a planned feature in the rewrite

**Comment by YuraJE4K** [comment]
I like the idea, but since that will take off the fun i have another idea.maybe make a new command p!collection, which will show all pokemons we have in inventory, with all the filters including *--owned* and *--unowned*.

**Comment by person583375239** [comment]
> This is a planned feature in the rewrite

I'm a bit sad to hear that! I personally wouldn't mind evolved pokemon being considered caught, but I don't like the idea of traded ones doing the same. Oh well!
