### ISSUE TITLE
Paras labelled incorrectly. 

### ISSUE THREAD

**Issue by MusingStar** [poketwo/poketwo#208]
A paras appeared in a server as a wild pokemon, but the bot stated it's the incorrect pokemon and won't allow it to be caught.
![image](https://user-images.githubusercontent.com/25324837/119168945-12fd1980-ba27-11eb-94b1-a17ef2f4a4f5.png)
![image](https://user-images.githubusercontent.com/25324837/119169001-24462600-ba27-11eb-96d7-2692de4ddb11.png)

**Comment by ShinyWobbuffet** [comment]
any updates? when it fled, what did it say it was?

**Comment by MusingStar** [comment]
It never fled. The bot never stated that the paras fled, however, at 11:25 am CST, another wild pokemon showed up, and was caught with the proper name. So, I don't know what happened with the Paras.

**Comment by MusingStar** [comment]
Is there a time limit on when they flee? I didn't actually try to catch the pokemon until 5 minutes after it showed up, but no other pokemon had appeared, and there wasn't any message that stated the pokemon fled.

**Comment by person583375239** [comment]
The incorrect image issue has been happening very occassionally for a looong time (probably since bot inception), it's pretty rare though. I don't know why this happens, but it would be cool to get a fix for the wrong image being shown. If you use p!hint when you have this situation, you will be able to work out what pokemon has actually spawned and just catch based on that, ignoring the incorrect image.

In terms of pokemon fleeing,  this should only ever happen when a new pokemon spawns in the same channel. If a new one doesn't appear in the same channel, then the originally spawned pokemon should remain catchable forever. In theory anyway. (In reality, sometimes the poketwo bot goes down and wipes the current spawn statuses, but this has been rare as of late I believe)

**Comment by WitherredAway** [comment]
I believe this happens when the bot or discord itself lags and the bot fails to send the spawn message but still registers the spawn which i doubt is fixable. In case of such, do p!hint and try to figure out from that
