### ISSUE TITLE
Allow pokemon received via other mode than catch add in pokedex & get coins

### ISSUE THREAD

**Issue by ihemantkumar** [poketwo/poketwo#211]
Issue:
Right now only pokemon caught in added in pokedex & we get pc as per current catch count. 

Request:
To allow pokemon received via other mode than catch add in pokedex & get coins. Method to aquire pokemon could be trade/voting gift box/ buy from auction or marketplace or evolution. Currently, we can't really enjoy pokemon evolution, as it won't get registered in dex. Weird!!!!

The pokemon count in `p!profile` doesn't match with actual pokemon count in bag. 

Can we have this feature please?

**Comment by User83285u92** [comment]
See issue #203 for adding Pokemon you didn't catch to dex. My opinion of this is it would be **way** too easy to earn coins in this fashion. People could just trade Pokemon from account to account and get infinite amount of coins, quite broken. Also, having trades add to Pokedex takes away from a lot of the fun in completing dex, all the challenge is gone.

For profile it says "Pokemon **caught**" not Pokemon owned, so it wouldn't make sense to change this feature. If you want to see your Pokemon owned do `p!p`.

**Comment by ihemantkumar** [comment]
I am not sure what are you picturing about the amount of pc we get. But it's sure much less than some players make by buying pokemon in less and selling for high price.

For the rest of the players it will be a good opportunity to complete the pokedex and in the process have more fun.

Tbh, I had also started evolving pokemon when I started playing pokeTwo then more experienced players told me that it's useless to evolve pokemon coz they won't make it to pokedex and you won't even get coins for new pokemon. So I stopped doing it.... Means the only way to play game is only catch pokemon. The rest features are some add-ons.

**Comment by Kuraven** [comment]
We already have a market inflation issue due to the rise in pc in circulation. We don't need more sources of money/more money in circulation. (This is also thanks to autocatchers and shameless cheaters who buy stuff from them). Not only that, but what User said is also true. You could just buy a pichu for, say, 30 pc, and then get 35 pc for the dex entry. He could spam a bit to evolve it, and get another 70 pc (because of Pikachu and Raichu). Same for any other pokemon. Not only is that 1 issue, you would also be able to buy 1000 pokemon from the market and then get the 35k pc award for registering 1k of a certain pokemon. You could easily go for something like Fletchling or some other cheap, 2-3 pc pokemon. Your net profits would be 32-33k. Adding this feature would also give autocatchers the opportunity to threaten the game itself by flooding the market with every random pokemon they get, at the price of 1 pc per pokemon. Evrryone would have the entire dex conpleted, and that would be one less feature on he bot. Coming back to the idea of the dex; something like this would make it easy as all hell to complete the dex. You wouldn't even have to try. Completing it would just be a participation award, and completing it wouldn't matter anymore.

Also, a similar issue has been made before. It was promptly turned down.
