### ISSUE TITLE
Edit bug

### ISSUE THREAD

**Issue by TiagoIsSneaky** [poketwo/poketwo#337]
**Describe the bug**
When you edit a message and it has a filter in it, poketwo will say invalid int value '(filters added)

**To Reproduce**
Type p!p or p!m s and send, and then edit them and add a filter like --sh
**Expected behavior**
It is supposed to send the command properly instead of sending an error message.
**Screenshots**

https://media.discordapp.net/attachments/869290013022650378/914136397403807754/IMG_0119.png

https://media.discordapp.net/attachments/869290013022650378/914136902616109117/IMG_0120.png

**Comment by pikaninja** [comment]
Looks like this is a cause of the fact that you used the apple --, not the normal one
This works in normal invocations due to [these lines](https://github.com/poketwo/poketwo/blob/master/bot.py#L130-L133):
Which aren't in the edit one: [here](https://github.com/poketwo/poketwo/blob/master/cogs/bot.py#L60-L63).

Pretty easy fix if someone wants to pull request it I guess.
