### ISSUE TITLE
"Market is temporarily disabled for your account. Check back Later"

### ISSUE THREAD

**Issue by Killk06** [poketwo/poketwo#404]
**Describe the bug**
So when I went to try and use the command to buy a pokemon it came up with that

**To Reproduce**
I don't know what you need to do

**Expected behavior**
I expected it to just buy the Pokemon

**Screenshots**

**Additional context**

**Comment by WitherredAway** [comment]
Hey there, market is currently disabled for bug fixing. However, the developer has other higher priorities right now. Market will be back up as soon as possible, sorry for the inconvenience.

**Comment by IsraelLevi12** [comment]
Hi sorry to bother you more I'm getting into poketwo support because my market doesn't work. It was always like that I always had to ask my friends to buy a poketwo. It was always like that I always had to ask my friends to buy a poketwo. The message was "For tour market is Disabled later check" .
I hope my problem is resolved.

**Comment by WitherredAway** [comment]
Hey there, please read the message i sent earlier!

**Comment by IsraelLevi12** [comment]
Okay 🙏🙂🙏

**Comment by MMMMMMMMTTYYY** [comment]
h

**Comment by MMMMMMMMTTYYY** [comment]
First of all i know this isnt gonna happen but its worth a try, im requesting a p!export command that gives you your pokemon in .pk2 files so you can bring them to the main games by using PKheX (you can only export not import*) it would give you the same amount of coins if you release them :)

**Comment by MMMMMMMMTTYYY** [comment]
i commented on the wrong one lmfaooo
