### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by mbearc** [poketwo/poketwo#470]
I have attempted to use the bot’s commands in my server, another server and my DMS with with bot, however the bot doesn’t respond, the bot however does spawn a pokemon, yet i can’t catch it because as I said, the commands aren’t working. I have used p!p, p!pokemon, P!p. p!time, p!c, p!catch, P!catch, p!h, p!vote. None of these have worked. It has been 3 days to my knowledge like this.

p!p no response, p!pokemon, no response, p!time no response, p!vote, no response.

I expected the bot to respond with the appropriate commands.

![D247F693-928E-48F7-88C1-7EA334DA4AC4](https://user-images.githubusercontent.com/112750662/188262058-785089d2-b9f9-4225-a194-dbaf7ea844f1.png)
![EE6606FA-D2F2-43DC-A72B-0EE325D19A67](https://user-images.githubusercontent.com/112750662/188262059-435c4294-1b9f-430a-bb7f-dd7535e69b0e.png)
![0BE7AAAC-0FAA-4EF5-BFD8-526D38E232D7](https://user-images.githubusercontent.com/112750662/188262061-1b2c580d-d949-4567-b74d-16d47c4672f0.png)

**Comment by oliver-ni** [comment]
Hi! Due to [recent changes by Discord](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ), Pokétwo can no longer see message content outside of DMs unless the bot user is mentioned in the message. Thus, you are now required to use the bot mention as a prefix, e.g. `@Pokétwo vote` instead of `p!vote`.

We made this prefix change two weeks ago in anticipation of message content deprecation; if you ran a command with the `p!` prefix within those two weeks, there was a notice informing you of the change. We also announced this on our [community server](https://discord.gg/poketwo). If you'd like to hear more about the change, please join the server and scroll up in the #bot-news channel.
