### ISSUE TITLE
Poketwo is being picky

### ISSUE THREAD

**Issue by AL675-765** [poketwo/poketwo#529]
**Describe the bug**
Poketwo on my freind server is being picky about who catches a pokemon, someone else on the server tried to catch the pokemon but it was being weird and was not responding. Even though they spelled the name correctly.

**To Reproduce**
The pokemon that apeared was a squawkabilly, specificly a green one.

**Expected behavior**
To have the other person who spelled it correctly first catch the pokemon.

**Screenshots**
![Screenshot_20230721_142433_Discord](https://github.com/poketwo/poketwo/assets/140211640/8a3d2a7b-26ab-44ea-8e32-ef3cd6f812b8)

![Screenshot_20230721_145347_Discord](https://github.com/poketwo/poketwo/assets/140211640/136c62c9-99c8-4563-b190-6e78c328dfd9)

**Comment by Vigentian** [comment]
If the bot isn't responding to your friend's commands, it's probably because they were mentioning the bot's role (which is also named Pokétwo by default) instead of the bot itself. You can check by clicking on the mention; if the bot's profile doesn't appear, then it was a role mention. I'd recommend changing the name of the Pokétwo role in your server to prevent similar problems from occurring in the future.
Additionally, there is only one form of Squawkabilly currently implemented in the bot, which can be caught with the name `Squawkabilly`.

**Comment by InInfinitumEtInTenebris** [comment]
Why was this closed? It still doesn't work properly 3 years later lol
