### ISSUE TITLE
I can't change the pokemone I wish to favorite

### ISSUE THREAD

**Issue by glitchbot12** [poketwo/poketwo#575]
**Describe the bug**
Poketwo has a problem when trying to change the favorite pokemon from the starter. I tried to change it three times with the followed directions but no matter what pokemon I choose, it ends up choosing the starter pokemon. 

**To Reproduce**
Follow the change favorite instructions and when you choose a different pokemon unrelated, it will go back to the one you started with. 

**Expected behavior**
It says your supposed to be able to change the pokemon you want to favorite. 

**Screenshots**
![Screenshot 2023-12-30 131926](https://github.com/poketwo/poketwo/assets/69097558/b6cf87b0-9de1-4188-8b56-336459d83bb3)
![Screenshot 2023-12-30 131944](https://github.com/poketwo/poketwo/assets/69097558/171dc1ea-30ef-4aa3-944b-cef2d21e99e4)

**Additional context**
I am in a private server so I'm not sure if that affects anything.

**Comment by WitherredAway** [comment]
Not a bug, you need to specify which pokemon exactly you want to un/favorite by using its ID in the inventory
![IMG_20231231_025619](https://github.com/poketwo/poketwo/assets/81734495/27999bce-a83a-43e0-abb6-a874a4b33096)
E.g. `@‌Pokétwo#8236 favorite 4` in order to favorite your gothita that is at number 4

This is necessary because you can have many different pokemon of the same species, so just specifying the name would not work as it wouldn't know which one you are referring to.
