### ISSUE TITLE
Economic Control and Recovery via Raffle System

### ISSUE THREAD

**Issue by cillosis** [poketwo/poketwo#67]
**MARKET RECOVERY IDEA**
===================

**PROBLEM:** 

Due to the introduction of shards, the economy is losing currency. When pc is spent on a shard, that money disappears effectively from existence. As a result, the supply of goods increases, while the currency pool decreases resulting in value of goods being reduced.

**SOLUTION:**

Instead of pc spent on shards disappearing, I propose that the pc be added to a raffle “pot”. This will effectively reintroduce currency into the market. A few implementation notes:

1. If market is deflated, you can subsidize the jackpot with additional PC. For example, for every 1pc spent, put 2pc into the pot.
2. If market is inflated, you reduce the pot by adding less. So for each 2pc spent, only add 1pc to the pot.
3. The drawing for the raffle should be automatic and fairly frequent. If the drawing is infrequent, then single users may gain large amounts of pc and hoard it rather than invest back into economy. Based on a rough guess (without data), I would think every 6 hours would be sufficient for a drawing. This could of course be adjusted based on the amount of pc spent on shards within a raffle cycle.
4. To gain entry to a raffle, there are many ways to accomplish this. After some thought, I think the best way to do it and discourage the usage of alt accounts, would be to make it part of the “post-catch” logic. So, for example after typing catch command, the bot then determines the IV distribution as well as if it is a shiny. Additionally it could determine if a raffle ticket is earned. The raffle ticket would be automatically entered (not tradeable). In this way, for a user to try to “game” the system with an alt account, they would need to catch pokemon, which they might as well do with their main account anyway.

I believe after some thought, this would not only help restore the bot economy, but also provide a mechanism to inflate/deflate as necessary.

**Comment by oliver-ni** [comment]
Thank you for the proposal—I will consider. Other community members, please feel free to give your input here as well.

**Comment by infinitiive** [comment]
Considering the recent economic problems on Pokétwo, I really like this idea and I think any attempt to fix the economy is a welcome one. Though I’m not sure pc lost to shards is the reason for the decline, a raffle could be a good way to recirculate pc that might otherwise be lost. If this is implemented I would advocate against stacked raffle tickets because this would give incentive for users to stack tickets on alts and attempt to game the system, though this is likely inevitable to some degree. Whether raffles are opt-in or not would also be something to consider, in terms of whether or not a user gets a choice as to when to use their tickets or if they are automatically applied.

**Comment by cillosis** [comment]
In my opinion, the raffle ticket would be automatically entered the moment it is gained. And there would not be a limit to number of entries. In other words, the more active a player is, the higher chance of winning the raffle. I agree having the tickets be in an inventory and stackable would be counter-productive in this system.

**Comment by infinitiive** [comment]
> In my opinion, the raffle ticket would be automatically entered the moment it is gained. And there would not be a limit to number of entries. In other words, the more active a player is, the higher chance of winning the raffle. I agree having the tickets be in an inventory and stackable would be counter-productive in this system.

That’s a really interesting suggestion, I hadn’t considered the angle of multiple entries per person. I feel it would definitely provide a greater catching incentive for a lot of users, and at that point the use of alts becomes pretty unnecessary if you can increase your odds substantially using just one account.

**Comment by michaelsong4399** [comment]
Cillosis presents an interesting idea. I would definitely enjoy having a participation-based lottery system (being a person who's online 247) and I can definitely see how it can increase player activity. However, I would also like to point out a few details about our economy that we can consider before we implement this lottery system.

**1. What is this "problem" that everyone is talking about?**
Recently, the community saw a sharp decrease in market/auction prices of shiny and rare Pokemons. What used to be 40-50k became only 28k in market and barely 20k in auctions. We may also see that the price-check manuals feel "overpriced" and outdated, pricing 90+iv's at 15k rather than the current market value of a bit under 10k.

**2. Is this really a problem?**
In an economics standpoint - no, not really. Since currencies are placeholders of value, it's not that everyone is getting poorer, but that the money is increasing in value due to the Pokemon amount (GDP) is increasing way faster than the money supply. We have a surplus in Pokemons.
Now, we are not too worried at this problem from a micro standpoint. Individuals are still able to freely trade and buy at the market price and no value is lost through this process.
But, if we think about this problem long-term with macro standpoint, the economy is entering a recession. What we are currently experiencing is decreased interest in producing (catching Pokemons) and lowered demand in markets/auctions. Eventually, this recession is going to limit productivity and further decrease the market price.

**3. Why did this happen?** (My opinions)
Instead of pc "disappearing" from shard-buying, it is really the gaining of pc that causes this problem. In this community, the only way to earn pc is from completing Pokedex at catches: 1, 10, 100, and 1000. The rewards are set at: 35, 350, 3500, and 35000, respectively. This system makes it so that each Pokemon is base-priced at 35 pc. However, if we do a quick estimation of the average value of Pokemon in this server from the values provided by OIiver on 11/22 (897,765,359pc / 43,609,868pokemons,) we get 20.59 pc per Pokemon. This means that the value of money has increased 70% (35/20.59-1). To verify this, if we multiply the price of a current low demand shiny (28k ish) by 1.7, we get about 47.5k, which is very close to the past price for shinies.
And the problem happens here: even though it may seem like each Pokemon is 35pc from the Pokedex, this payout is delayed. In order to receive that reward, players have to work increasingly hard in order to get to that catch amount. This problem was small when the economy was in its early stages because most players had time to catch the 10th, or even 100th needed in order to get to that reward. However, when it comes to the gap between 100 and 1000th Pokemon, most players get stuck. In order to get to a few 1000th Pokemon rewards (not including shiny hunt favoritism), you need to catch at least 160k Pokemons. The number of players who has exceeded that catch number on this server can be counted by both hands. The majority of the active players get stuck somewhere between the 100th and 1000th catch and don't get their 35k pc reward in time.
This has caused a significant gap between the Pokemon count and pc supply that seemingly decreased market equilibrium price.

**4. How can we solve this issue?**
In the past, government systems have helped recessions by funding public infrastructure and creating more job opportunities (well clearly we don't have that here). However, what we can do is something like this:

1. Change/add ways players earn pc from the server. (Fix Pokedex reward system, add Quest rewards,... etc.)
2. You can do something like a lottery system to temporarily boost server economy, but this will only be a short term solution. Overdoing this can also lead to major imbalances between player wealth. (Needs a lot of work and consideration before implementation)

Apart from this, I don't think we should interfere with the economy too much. After all, it's the invisible hand doing its job.

Above are my personal thoughts and opinions. (Please don't ban me)

(I totally did not write an entire AP Econ Essay/FRQ.)

**Comment by infinitiive** [comment]
> In this community, the only way to earn pc is from completing Pokedex at catches: 1, 10, 100, and 1000. 
I think your analysis is spot on, but I'm curious as to how pc earned by boxes/voting factors into your economic calculations? After all, pc is the most common reward for boxes and likely serves as a means of building income for many players.

**Comment by michaelsong4399** [comment]
> Provide additional milestones for catch bonuses and make catch bonuses less linear.
> I think the above point can be generally agreed on. For more specifics, I would suggest having milestones added in at 50/250/500/2,500/5,000/10,000. Speaking from personal experience, it'd be quite ridiculous to make it to 10,000 catches of a specific pokemon, but it's certainly possible given enough time.
> 
> 1st catch - 35pc
> 10 catches - 350pc (315pc for 9 catches, ~39pc each)
> 25 catches - 600pc (600pc for 15 catches, 40pc each)
> 50 catches - 1,050pc (1050c for 25 catches, 42pc each)
> 100 catches - 2,250pc (2250pc for 50 catches, 45pc each)
> 250 catches - 7,500pc (7500pc for 150 catches, 50pc each)
> 500 catches - 13,750pc (13750pc for 250 catches, 55pc each)
> ...

> The numbers can definitely be tinkered with, but this should give a general idea of what I had in mind. Alts play far too large of a role in Poketwo currently, and pokecoin income has become too sparse in a system that's been heavily impacted by market/auctions/shard usage.

As stated by redpandacactus, the current piece-wise reward system has caused issues relating to frequent alt-account using to reap early benefits as well as the long-term delayed payout issue. As illustrated in the graph below, even though it seems like each Pokemon is rewarded by 35pc, the average reward decreases significantly (to 3pc per Pokemon) until a new step is reached. With the increasing margins, a longer time and effort (by 10x) is also needed in order to achieve the next reward.

![Screen Shot 2020-12-10 at 1 11 44 AM](https://user-images.githubusercontent.com/46873721/101728603-adbef880-3a84-11eb-8baa-b52429609daf.png)
*(X axis: # distinct Pokemon caught, Y axis: reward per Pokemon caught)*



After a short exchange of ideas with redpandacactus, we propose (and it's a proposal, **NOT** official) a new economy system consisting of a **set reward** for each catch and a smaller **piecewise reward** to still keep the new players motivated. Below are the changes we suggest.

1. A set reward for each catch, approximately equal (or slightly under) market average price per Pokemon. As established in a previous post, it could be somewhere around 20pc. (but must be recalculated based on new statistics) If set to any price too far from the equilibrium market price, it will be unfair to players with majority of their wealth in pc vs. players who save wealth in special/shiny Pokemons. This also eliminates alt accounts exploiting the early-reaping of piecewise rewards.

2. A piecewise reward may still be implemented, but should not account for a big part of economy and could even be cosmetic/badge/perk rewards based on individual or total catch count. This form of reward still provides the incentive for new players to progress through the game while decreases the benefits from setting up and abusing many alt-accounts.

Overall, we hope this new addition can significantly stabilize the available currency supply to a level proportional to our GDP. (Pokemons produced)

Once again, these are **not official** server decisions, but merely suggestions provided by our lovely community. 
Please feel free to comment your ideas and suggestions below, as we all know these plans are far from perfect.

Thanks.

**Comment by kyle-he** [comment]
Interesting stuff, but I think the problems here are a bit outdated, so I will be closing this.
